import {
  Target,
  Cloud,
  Activity,
  Wifi,
  Cpu,
  Shield,
  Zap,
  Settings,
  Database,
  Globe,
  Lock,
  Server,
  Smartphone,
  Monitor,
  HardDrive,
  Radio,
  Bluetooth,
  Battery,
  Gauge,
  Thermometer,
  Droplets,
  Wind,
  Sun,
  Moon,
  Eye,
  Bell,
  Clock,
  Calendar,
  Map,
  Navigation,
  Layers,
  Box,
  Package,
  Truck,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  ArrowUpRight,
  ArrowRight,
  CheckCircle,
  AlertTriangle,
  Info,
  Star,
  Heart,
  Bookmark,
  Download,
  Upload,
  RefreshCw,
  Search,
  Filter,
  Sliders,
  ToggleLeft,
  Power,
  Plug,
  Cable,
  CircuitBoard,
  Cog,
  Wrench,
  Hammer,
  Lightbulb,
  Flame,
  Waves,
  // Development & Code
  Code,
  Terminal,
  GitBranch,
  Github,
  GitCommit,
  GitMerge,
  GitPullRequest,
  // Components & Frameworks
  Boxes,
  Blocks,
  Component,
  // Industry & Process
  Factory,
  Rocket,
  FlaskConical,
  Workflow,
  GitCompare,
  // Communication
  MessageCircle,
  Mail,
  Phone,
  Send,
  MessageSquare,
  // Media & Files
  Image,
  File,
  FileText,
  Folder,
  FolderOpen,
  Film,
  Music,
  Video,
  // Actions
  Plus,
  Minus,
  X,
  Check,
  Trash2,
  Edit,
  Edit3,
  Save,
  Copy,
  Clipboard,
  // Users & People
  User,
  Users,
  UserCircle,
  UserPlus,
  UserCheck,
  // Places & Buildings
  Home,
  Building,
  Building2,
  Store,
  Warehouse,
  // Education & Achievement
  Award,
  GraduationCap,
  BookOpen,
  Book,
  // Tools & Utilities
  PenTool,
  Pencil,
  Brush,
  Palette,
  Scissors,
  // Navigation & Movement
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  MoveHorizontal,
  MoveVertical,
  // Status & Indicators
  Loader,
  Loader2,
  Sparkles,
  Zap as Lightning,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  target: Target,
  cloud: Cloud,
  activity: Activity,
  wifi: Wifi,
  cpu: Cpu,
  shield: Shield,
  zap: Zap,
  lightning: Lightning,
  settings: Settings,
  database: Database,
  globe: Globe,
  lock: Lock,
  server: Server,
  smartphone: Smartphone,
  monitor: Monitor,
  harddrive: HardDrive,
  radio: Radio,
  bluetooth: Bluetooth,
  battery: Battery,
  gauge: Gauge,
  thermometer: Thermometer,
  droplets: Droplets,
  wind: Wind,
  sun: Sun,
  moon: Moon,
  eye: Eye,
  bell: Bell,
  clock: Clock,
  calendar: Calendar,
  map: Map,
  navigation: Navigation,
  layers: Layers,
  box: Box,
  package: Package,
  truck: Truck,
  barchart3: BarChart3,
  barchart: BarChart3,
  linechart: LineChart,
  piechart: PieChart,
  trendingup: TrendingUp,
  arrowupright: ArrowUpRight,
  arrowright: ArrowRight,
  checkcircle: CheckCircle,
  alerttriangle: AlertTriangle,
  info: Info,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  refreshcw: RefreshCw,
  search: Search,
  filter: Filter,
  sliders: Sliders,
  toggleleft: ToggleLeft,
  power: Power,
  plug: Plug,
  cable: Cable,
  circuitboard: CircuitBoard,
  cog: Cog,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  flame: Flame,
  waves: Waves,
  // Development & Code
  code: Code,
  terminal: Terminal,
  gitbranch: GitBranch,
  github: Github,
  gitcommit: GitCommit,
  gitmerge: GitMerge,
  gitpullrequest: GitPullRequest,
  // Components & Frameworks
  boxes: Boxes,
  blocks: Blocks,
  component: Component,
  // Industry & Process
  factory: Factory,
  rocket: Rocket,
  flaskconical: FlaskConical,
  flask: FlaskConical,
  workflow: Workflow,
  gitcompare: GitCompare,
  // Communication
  messagecircle: MessageCircle,
  message: MessageCircle,
  mail: Mail,
  phone: Phone,
  send: Send,
  messagesquare: MessageSquare,
  // Media & Files
  image: Image,
  file: File,
  filetext: FileText,
  folder: Folder,
  folderopen: FolderOpen,
  film: Film,
  music: Music,
  video: Video,
  // Actions
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  trash2: Trash2,
  trash: Trash2,
  edit: Edit,
  edit3: Edit3,
  save: Save,
  copy: Copy,
  clipboard: Clipboard,
  // Users & People
  user: User,
  users: Users,
  usercircle: UserCircle,
  userplus: UserPlus,
  usercheck: UserCheck,
  // Places & Buildings  
  home: Home,
  building: Building,
  building2: Building2,
  store: Store,
  warehouse: Warehouse,
  // Education & Achievement
  award: Award,
  graduationcap: GraduationCap,
  graduation: GraduationCap,
  bookopen: BookOpen,
  book: Book,
  // Tools & Utilities
  pentool: PenTool,
  pencil: Pencil,
  brush: Brush,
  palette: Palette,
  scissors: Scissors,
  // Navigation & Movement
  chevronright: ChevronRight,
  chevronleft: ChevronLeft,
  chevrondown: ChevronDown,
  chevronup: ChevronUp,
  movehorizontal: MoveHorizontal,
  movevertical: MoveVertical,
  // Status & Indicators
  loader: Loader,
  loader2: Loader2,
  sparkles: Sparkles,
};

interface DynamicIconProps {
  name: string;
  className?: string;
  size?: number;
  style?: React.CSSProperties;
}

export default function DynamicIcon({ name, className, size, style }: DynamicIconProps) {
  if (!name) return <span className={className} style={style}>⚡</span>;

  // Normalize: remove spaces, dashes, lowercase
  const key = name.replace(/[-\s]/g, '').toLowerCase();
  const IconComponent = iconMap[key];

  if (IconComponent) {
    return <IconComponent className={className} size={size} style={style} />;
  }

  // If it's an emoji or special character, render as-is
  if (name.length <= 2 || /[\u{1F000}-\u{1FFFF}]/u.test(name)) {
    return <span className={className} style={style}>{name}</span>;
  }

  // Fallback: render the text
  return <span className={className} style={style}>{name}</span>;
}

// Export iconMap for use in IconPicker
export { iconMap };
